### ISSUE TITLE
Add DNN Store Modules on DNN Version 9.2.0.366-777 throws error

### ISSUE THREAD

**Issue by CPQcart** [lepigocher/DNNStore#2]
Installed Extension Store_03.02.01_Install.zip ON DNN Version DNN_Platform_9.2.0.366-777_Install
Info Installation committed
Info Installation successful. - DotNetNuke.Store Menu
Info Deleted temporary install folder
EndJob Installation successful.
<<<Add Module Store Catalog 
Error "A critical error has occurred. Please check the Event Viewer for further details."
 http://dev0920366777.dnndev.me/Default.aspx?tabid=35&error=Method+not+found%3a+%27Void+DotNetNuke.Common.Utilities.DataCache.SetCache(System.String%2c+System.Object%2c+Boolean)%27.&content=0
Log has:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c4e88ec1-4222-45f4-a2b9-ba20e676264f
AssemblyVersion:9.2.0
PortalId:0
UserId:1
TabId:35
RawUrl:/Store-Admin
Referrer:http://dev0920366777.dnndev.me/Store-Admin
UserAgent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
ExceptionHash:69jFZdTp/EaHYgRMoMVdgK8NgVo=
Message:Method not found: 'Void DotNetNuke.Common.Utilities.DataCache.SetCache(System.String, System.Object, Boolean)'.
StackTrace:
InnerMessage:Method not found: 'Void DotNetNuke.Common.Utilities.DataCache.SetCache(System.String, System.Object, Boolean)'.
InnerStackTrace:
at DotNetNuke.Modules.Store.Admin.StoreController.GetStoreInfo(Int32 portalID) at DotNetNuke.Modules.Store.Components.StoreControlBase.get_StoreSettings() at DotNetNuke.Modules.Store.WebControls.Store.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vmCC677EC
<<<< Store Catalog error also
http://dev0920366777.dnndev.me/Default.aspx?tabid=33&error=Method+not+found%3a+%27Void+DotNetNuke.Common.Utilities.DataCache.SetCache(System.String%2c+System.Object%2c+Boolean)%27.&content=0
Store Menu BELOW Catalog   Same error
 Store Mini Cart BELOW Store Menu

Lee

**Comment by lepigocher** [comment]
Hello,

I need a few days to look at this!

Thanks

**Comment by CPQcart** [comment]
Gilles :
Do you do any Contract work on DNN Modules?
If so what is your hourly rate?
I have a contract programmer that developed 90% of a module but when I wanted the manually copied file do within the  VSIX installer he is leaving me hanging.
Work would be done on a Root access server.
Thanks in advance.
Lee

**Comment by lepigocher** [comment]
Hi Lee,
Sorry for the delay but your email was in the spam box ! :(
It depends of your needs, I could help you but before speaking of money I need to know your needs !I'm verry surprised you talked about a VSIX because no one use this Visual Studio feature to deploy a module !? I don't know if you are confused with something else or if your programmer is not a real DNN specialist.Tell me where you live (to compute the time shift) and I will try to organize a meeting with Team Viewer. If you don't know Team Viewer it's a software similar of Goto Meeting used to connect two computer like if we was close to each other in a meeting room. You have to download and install the free version before the meeting.
Regards,
Gilles

    Le ‎samedi‎ ‎28‎ ‎avril‎ ‎2018‎ ‎23‎:‎25‎:‎49‎ ‎CEST, CPQcart <notifications@github.com> a écrit :  
 
 
Gilles :
Do you do any Contract work on DNN Modules?
If so what is your hourly rate?
I have a contract programmer that developed 90% of a module but when I wanted the manually copied file do within the VSIX installer he is leaving me hanging.
Work would be done on a Root access server.
Thanks in advance.
Lee

**Comment by CPQcart** [comment]
Gilles:
The company that the old programmer works for has assigned a NEW programmer to Fix the pending issues so my request in no longer needed.
Thanks for the response.
Lee

**Comment by CPQcart** [comment]
Do you have any updates on My post 4 Apr were errors occur in DNN Version DNN_Platform_9.2.0.366-777_Install  Thanks in advance for any update Lee
