### ISSUE TITLE
throws error when you Add DNN Store Modules Ver 03.02.01 on DNN CE Version 9.2.0.366-777 

### ISSUE THREAD

**Issue by CPQcart** [lepigocher/DNNStore#3]
My post on Apr 4 was closed & this is still an issue
Installed Extension Store_03.02.01_Install.zip ON DNN Version DNN_Platform_9.2.0.366-777_Install
Info Installation committed
Info Installation successful. - DotNetNuke.Store Menu
Info Deleted temporary install folder
EndJob Installation successful.
<<<Add Module Store Catalog
Error "A critical error has occurred. Please check the Event Viewer for further details."
http://dev0920366777.dnndev.me/Default.aspx?tabid=35&error=Method+not+found%3a+%27Void+DotNetNuke.Common.Utilities.DataCache.SetCache(System.String%2c+System.Object%2c+Boolean)%27.&content=0
Log has:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c4e88ec1-4222-45f4-a2b9-ba20e676264f
AssemblyVersion:9.2.0
PortalId:0
UserId:1
TabId:35
RawUrl:/Store-Admin
Referrer:http://dev0920366777.dnndev.me/Store-Admin
UserAgent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
ExceptionHash:69jFZdTp/EaHYgRMoMVdgK8NgVo=
Message:Method not found: 'Void DotNetNuke.Common.Utilities.DataCache.SetCache(System.String, System.Object, Boolean)'.
StackTrace:
InnerMessage:Method not found: 'Void DotNetNuke.Common.Utilities.DataCache.SetCache(System.String, System.Object, Boolean)'.
InnerStackTrace:
at DotNetNuke.Modules.Store.Admin.StoreController.GetStoreInfo(Int32 portalID) at DotNetNuke.Modules.Store.Components.StoreControlBase.get_StoreSettings() at DotNetNuke.Modules.Store.WebControls.Store.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: xxxx
Thanks in advance for your support for this module 
Lee

**Comment by lepigocher** [comment]
Please look at this : https://github.com/lepigocher/DNNStore/releases/tag/04.00.00

**Comment by CPQcart** [comment]
lepigocher:
Thanks for the update.
After two failed Extension installs of Store_04.00.00_Install , attempts on DNN Ver 09.02.01 (533) , Persona Bar doesn't work, refresh page get Error
Server Error in '/' Application.
Could not load file or assembly 'DotNetNuke.Modules.Store.Core.Cart.AtosProvider' or one of its dependencies. An attempt was made to load a program with an **incorrect format**.
...
It is there at C:\DevNew\DevN09.DnnDev.Me\DesktopModules\Store\Providers\GatewayProviders\AtosProvider
set security all & above
3rd try set security on AtosProvider
has DNN msg 'There was an error retrieving your content. Please check your internet connection'
Then Refresh page same error
<< more of error
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
**Assembly Load Trace: The following information can be helpful to determine why the assembly 'DotNetNuke.Modules.Store.Core.Cart.AtosProvider' could not be loaded.**
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by CPQcart** [comment]
lepigocher:
In updating my notes I saw DNN 7.4.2 to 9.2.0
So did an install in DNN v. 09.02.00 (366)
and get the same behavior & error.
Lee

**Comment by lepigocher** [comment]
It work perfectly with DNN 09.02.00 (366) but NOT with DNN 09.02.01!!!
As usual, one of the "great" guys behind DNN Platform decided to remove support of 32bits. So that's why it do not work, I have to prepare a new version to correct this.

**Moreover, this will be the VERY LAST release from me. I DO NO LONGER work with DNN and I do not have times to works on this. I spent all my summer holidays on this last version to allow current users to have time to change for another module. So please use something else for your projects.**

**Comment by CPQcart** [comment]
Gillles:
Thanks for the feedback.
Will you advise DNN that they need to find someone to support the app the has DNN Copyright & the Doc can not be modified.

Lee Hinman
e Market Places LLC
WWW.CPQcart.com
Voice:850-588-1724
Cell:   850-230-5601
FAX:  850-588-1725
US Utility Patent 7747469

**Comment by lepigocher** [comment]
I have **NOT to advise** anyone because DNN Software **DID NOT help** on this module **from YEARS**!
Because the module is Open Source, you have the full source code and you can use it and off course modify it. The current copyright is maintened because of legal reasons but DNN Software have NEVER helped on this module from at least 10 YEARS.
They even closed and archived the Store forum without taking a minute to warn me. So I do NOT have to be polite and considerate with people who are not with me!
I have maintained this module for years without gaining just 1 cent just to help the DNN users. Given the lack of onsideration that I have received in recent years and the reasons given previously, I no longer have the time or the will to continue.
